glosary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('virtualdict.urls')),

]

virtualdict/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.home,name="home"),
    path('concepts/',views.allconcepts,name="concepts"),
    path('concept/<int:concept_id>',views.concept,name="concept_view"),
    path('concept/comment/<int:concept_id>',views.concept_comment,name="concept_comment"),
    path('concept/reaction/<int:concept_id>',views.concept_reaction,name="concept_reaction"),
    path('defconcepts/',views.defconcepts,name="defconcepts"),
    path('concepts/user/<str:username>',views.userconcepts,name="userconcepts"),
    path('defconcepts/<int:concept_id>',views.concept_detail,name="concept_detail"),
    path('defconcepts/<int:concept_id>/delete',views.concept_delete,name="concept_delete"),
    path('newconcept/',views.newconcept,name="newconcept"),
    path('login/',views.lin,name="login"),
    path('register/',views.reg,name="register"),
    path('logout/',views.lout,name="logout"),
    path('profile/<str:username>',views.profile,name="profile"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

virtualdict/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Concepts(models.Model):
    title = models.CharField(max_length=200)
    definition = models.TextField(default="")
    exampleText = models.TextField(null=True, blank=True)
    exampleImg = models.ImageField(upload_to='posts_img/',null=True, blank=True)
    source = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title + " - " + self.user.username

class Reviews(models.Model):
    # V: Bien / F: Mal 
    review = models.BooleanField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    concept = models.ForeignKey(Concepts, on_delete=models.CASCADE)

    def __str__(self):
        return self.concept.title + " by " + self.concept.user.username + " - Review de " + self.user.username


class Comentarios(models.Model):

    texto = models.TextField(null=False)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    concept = models.ForeignKey(Concepts, on_delete=models.CASCADE)

    def __str__(self):
        return self.concept.title + " by " + self.concept.user.username + " - comentado por " + self.user.username

class ComentariosPerfil(models.Model):

    texto = models.TextField(null=False)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    user_perfil = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_perfil')
    comentador = models.ForeignKey(User, on_delete=models.CASCADE,related_name='comentador')

    def __str__(self):
        return self.user_perfil.username + " - comentado por " + self.comentador.username
    
class Perfil(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    foto = models.ImageField(upload_to='profile_pics/', null=True, blank=True)

    def __str__(self):
        return "perfil de " + self.user.username 
    

virtualdict/forms.py
from django import forms
from .models import Concepts,Reviews

class ConceptsForm(forms.ModelForm):
    class Meta:
        model = Concepts
        fields = ['title', 'definition', 'exampleText', 'exampleImg', 'source']
        widgets = {
            'title':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Cheetos',
                'required':'True',
                'autofocus':'True'
            }),

            'definition':forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'Los cheetos son...',
                'cols':'10',
                'rows':'5',
                'required':'True'
            }),

            'exampleText':forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'Hay varios tipos de cheetos...',
                'cols':'10',
                'rows':'3',
            }),


            'source':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'De los deseos',
            })
        }

class ReviewsForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['review']

virtualdict/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse, HttpRequest
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

from django.contrib.auth.models import User
from .models import Concepts, Reviews, Comentarios, ComentariosPerfil, Perfil
from .forms import ConceptsForm, ReviewsForm

# Create your views here.


def home(request):
    if User.is_authenticated:
        username = request.user

    return render(request, "home.html", {
        'username': username,
    })


def allconcepts(request):
    
    if request.method == "GET":
        concept = Concepts.objects.filter().order_by('-pk')[:1000]
        return render(request, "defconcepts.html", {
            'concept': concept,
            'global': True,
        })

    else:
        consulta = request.POST['search'] 
        if (consulta != "") and (consulta.isspace() == False):
         concept = Concepts.objects.filter(title__icontains=request.POST['search'])#.order_by('-pk')
        else:
         concept = Concepts.objects.filter().order_by('-pk')[:1000]
        return render(request, "defconcepts.html", {
            'concept': concept,
            'global': True,
        })


@login_required
def concept(request, concept_id):

    concept = get_object_or_404(Concepts, pk=concept_id)
    pos_reviews = Reviews.objects.filter(concept=concept, review=True)
    comentarios = Comentarios.objects.filter(concept=concept)
    neg_reviews = Reviews.objects.filter(concept=concept, review=False)
    user_review = None

    user_review = Reviews.objects.filter(
        concept=concept, user=request.user).first()

    comentarios_avanzados = []

    for comentario in comentarios:
        try:
            perfil = Perfil.objects.get(user=comentario.user)
        except Perfil.DoesNotExist:
            perfil = None

        # Agrega los resultados a la lista final
        comentarios_avanzados.append([perfil,comentario])
    
    print(comentarios_avanzados)
    return render(request, "concept.html", {
        'concept': concept,
        'positive': len(pos_reviews),
        'negative': len(neg_reviews),
        'user_review': user_review,
        'actual_user': request.user.username,
        #'comentarios': comentarios,
        'comentarios': comentarios_avanzados
    })

@login_required
def concept_comment(request,concept_id): 

    if request.method == "GET":
        return redirect("concept_view", concept_id=concept_id)
    else:
        concept = get_object_or_404(Concepts, pk=concept_id)
        comentado = request.POST['comentario'] 
        if (comentado != "") and (comentado.isspace() == False):
         comentario = Comentarios(texto=comentado,user=request.user, concept=concept)
         comentario.save()

        return redirect("concept_view", concept_id=concept_id)

@login_required
def concept_reaction(request, concept_id):

    if request.method == "GET":
        return redirect("concept_view", concept_id=concept_id)
    else:
        concept = get_object_or_404(Concepts, pk=concept_id)
        user_review = Reviews.objects.filter(
            concept=concept, user=request.user).first()
        reaccion = None

        if request.POST['reaction'] == "like":
            reaccion = True
        else:
            reaccion = False

        if user_review is None:
            # Crear una instancia de MiModelo
            nueva_review = Reviews(
                review=reaccion, user=request.user, concept=concept)

            nueva_review.save()
        else:
            if user_review.review == reaccion:
                user_review.delete()
            else:
                user_review.review = reaccion
                user_review.save()

        return redirect("concept_view", concept_id=concept_id)


@login_required
def defconcepts(request):
 
    if request.method == "GET":
        concept = Concepts.objects.filter(user=request.user).order_by('-pk')[:1000]
        return render(request, "defconcepts.html", {
            'concept': concept,
            'autor': True,
        })

    else:
        consulta = request.POST['search'] 
        if (consulta != "") and (consulta.isspace() == False):
         concept = Concepts.objects.filter(title__icontains=request.POST['search'],user=request.user)
        else:
         concept = Concepts.objects.filter(user=request.user).order_by('-pk')[:1000]
        return render(request, "defconcepts.html", {
            'concept': concept,
            'autor': True,
        })


@login_required
def userconcepts(request,username):
    user = get_object_or_404(User,username=username)
    autorizado = False
    if request.user.username == username:
      autorizado = True
    if request.method == "GET":
        concept = Concepts.objects.filter(user=user).order_by('-pk')
        return render(request, "defconcepts.html", {
            'concept': concept,
            'autor': autorizado,
        })

    else:
        consulta = request.POST['search'] 
        if (consulta != "") and (consulta.isspace() == False):
         concept = Concepts.objects.filter(title__icontains=request.POST['search'],user=user)
        else:
         concept = Concepts.objects.filter(user=user).order_by('-pk')[:1000]
        return render(request, "defconcepts.html", {
            'concept': concept,
            'autor': autorizado,
        })        


@login_required
def concept_detail(request, concept_id):
    if request.method == "GET":
        concept = get_object_or_404(Concepts, pk=concept_id, user=request.user)
        form = ConceptsForm(instance=concept)
        try:
            concept_img = concept.exampleImg.url
            return render(request, "concept_detail.html", {
                'concept_id': concept_id,
                'form': form,
                'concept_img': concept_img
            })
        except:
            return render(request, "concept_detail.html", {
                'concept_id': concept_id,
                'form': form,
            })
    else:
        try:
            concept = get_object_or_404(
                Concepts, pk=concept_id, user=request.user)
            form = ConceptsForm(request.POST, request.FILES, instance=concept)
            form.save()
            return redirect("defconcepts")

        except:
            return render(request, "concept_detail.html", {
                'concept_id': concept_id,
                'form': form,
                'message': "No sé qué pasó, pero no tenía que pasar D:"
            })


@login_required
def concept_delete(request, concept_id):
    if request.method == "GET":
        concept = get_object_or_404(Concepts, pk=concept_id, user=request.user)
        print(concept.title)
        return render(request, "concept_delete.html", {
            'concept_id': concept_id,
            'concept': concept
        })
    else:
        concept = get_object_or_404(Concepts, pk=concept_id, user=request.user)
        concept.delete()
        return redirect("defconcepts")


@login_required
def newconcept(request):
    if request.method == "GET":
        concept = Concepts.objects.filter(user=request.user)
        return render(request, "newconcept.html", {
            'form': ConceptsForm,
            'concept': concept
        })
    else:
        try:
            form = ConceptsForm(request.POST, request.FILES)
            nconcept = form.save(commit=False)
            nconcept.user = request.user
            nconcept.save()
            return render(request, "newconcept.html", {
                'message': "Guardado con éxito",
                'form': ConceptsForm
            })
        except:
            return render(request, "newconcept.html", {
                'message': "¡Uy! No se pudo guardar el concepto :(",
                'form': ConceptsForm
            })


def lin(request):
    if request.method == "GET":
        return render(request, "login.html")
    else:
        try:
            user = authenticate(
                request, username=request.POST['username'], password=request.POST['password'])
            if user is None:
                return render(request, "login.html", {
                    'error': "Usuario o contraseña incorrectos, intenta otra vez"
                })
            else:
                login(request, user)
                return redirect("home")

        except:
            return render(request, "login.html", {
                'error': 'Usuario o contraseña incorrectos, intenta de nuevo'
            })


def reg(request):
    if request.method == "GET":
        return render(request, "register.html")
    else:
        if " " in request.POST['username']:
            return render(request, "register.html", {
                'error': 'No se permiten espacios en el nombre de usuario'
            })
        elif len(request.POST['password']) < 6:
            return render(request, "register.html", {
                'error': 'Tu contraseña debe contener al menos 6 caracteres'
            })

        if request.POST['password'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], email=request.POST['email'], password=request.POST['password'])
                user.save()
                login(request, user)
                return render(request, "home.html", {
                    'username': user.username,
                })

            except Exception as e:
                print(e)
                return render(request, "register.html", {
                    'error': 'Algo salio mal :('
                })

        else:
            return render(request, "register.html", {
                'error': 'No coinciden las contraseñas'
            })


@login_required
def profile(request, username):

virtualdict/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Glossaryck</title>

    <!-- including bootstrap-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    
</head>

<head>
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" data-bs-theme="dark" id="navbar">
        <div class="container-fluid">
            <a href="/">
                <img class="navbar-brand" src="{% static '/images/glossaryc_face_ico.png' %}" id="logo">
            </a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'home' %} ">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'concepts' %}">Conceptos</a>
                </li>
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'defconcepts' %}">Mis Conceptos</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'newconcept' %}">Nuevo concepto</a>
                    </li>
                {% endif %}
                    
            </ul>

            <div class="ms-5">
                <ul class="navbar-nav">
                    <li class="nav-item py-2 py-lg-1 col-12 col-lg-auto">
                        <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                        <hr class="d-lg-none my-2 text-white-50">
                    </li>

                    
                    {% if user.is_authenticated %}
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' user.username %}">Perfil-{{user.username}}</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                    </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
                        </li>
                    {% endif %}
                    
                </ul>
              </div>
          </div>

          
            
        </div>
      </nav>
</head>

<body class="bcolor d-flex flex-column min-vh-100">
    {% block content %}
        
    {% endblock %}
</body>

<footer class="mt-auto" id="foot">
    <div class="container-fluid mb-5 mt-5">
        <!--h3>Glossaryck, coded with ❤ by Cherry</h3-->
    </div>

    <div class="container">
        <div class="row">
            <div class="col mb-3">
            </div>
          
              <div class="col mb-3">
          
              </div>
          
          
              <div class="col mb-3">
                <h5>Sitio</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="{% url 'home' %}" class="nav-link p-0">Inicio</a></li>
                  <li class="nav-item mb-2"><a href="{% url 'login' %}" class="nav-link p-0">Iniciar sesión</a></li>
                  <li class="nav-item mb-2"><a href="{% url 'register' %}" class="nav-link p-0">Registrarse</a></li>
                  <li class="nav-item mb-2"><a href="{% url 'concepts' %}" class="nav-link p-0">Conceptos</a></li>
                  {% if user.is_authenticated %}
                    <li class="nav-item mb-2"><a href="{% url 'defconcepts' %}" class="nav-link p-0">Mis conceptos</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'newconcept' %}" class="nav-link p-0">Nuevo concepto</a></li>
                  {% endif %}
                  
                </ul>
              </div>
          
              <div class="col mb-3">
                <h5>Links de interés</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="https://github.com/xinrin/django-glossaryck" target="_blank" class="nav-link p-0">GitHub</a></li>
                  <li class="nav-item mb-2"><a href="https://docs.djangoproject.com/en/4.2/" target="_blank" class="nav-link p-0">Django documentation</a></li>
                  <li class="nav-item mb-2"><a href="https://getbootstrap.com/" target="_blank" class="nav-link p-0">Bootstrap</a></li>
                  <li class="nav-item mb-2"><a href="https://www.postgresql.org/" target="_blank" class="nav-link p-0">PostgreSQL</a></li>
                </ul>
              </div>

        <div class="row">
            <div class="col-lg-6">
                <p style="margin-bottom: 0;">Todos los derechos reservados ©2023</p>
            </div>
                <div class="col-lg-6">
                    <a href="#" style="margin-bottom: 0;">Aviso de privacidad</a>
                </div>
        </div>
    </div>
    
</footer>


<script>
    var clicked = false
    addEventListener("DOMContentLoaded", () => {
        if(window.location.href.match(/defconcepts/g)){
            document.getElementById("btncollapse").classList.replace("offset-sm-8","offset-sm-1")
            if(document.body.scrollHeight < 1100){
            document.getElementById("btncollapse").classList.remove("fixed-bottom")
            }
        }
  
    })

    window.onscroll = function(){
        //console.log(window.scroll.toString)
        if(document.body.scrollTop > 50 || document.documentElement.scrollTop > 50){
            document.getElementById("navbar").style.padding = "1px, 1px"
            document.getElementById("navbar").style.opacity = "1"
            document.getElementById("logo").style.width = "35px"
        }else{
            document.getElementById("navbar").style.padding = "1px 1px"
            document.getElementById("navbar").style.opacity = "1"
            document.getElementById("logo").style.width = "70px"

        }

        if(window.location.href.match(/defconcepts/g)){
            var actualheight = document.body.scrollHeight - window.innerHeight - 50

            /*console.log("Inner Height:" + window.innerHeight)
            console.log("Scroll body height: " + document.body.scrollHeight)
            console.log("Scroll y:" + window.scrollY)
            console.log("Actual height:" + actualheight)*/

            if(window.scrollY == 0){
                document.getElementById("btncollapse").classList.replace("offset-sm-8","offset-sm-1")
                document.getElementById("btncollapse").classList.remove("fixed-bottom")
            }else{
                document.getElementById("btncollapse").classList.replace("offset-sm-1","offset-sm-8")
                document.getElementById("btncollapse").classList.add("fixed-bottom")
            }

            if(window.scrollY > actualheight){
            document.getElementById("newconcept").classList.add("disabled")
                if(clicked == false){
                    document.getElementById("collapseNewConceptBtn").click()
                    clicked = true
                }
            }else{
                document.getElementById("newconcept").classList.remove("disabled")
                if(clicked == true){
                    document.getElementById("collapseNewConceptBtn").click()
                    clicked = false
                }
            }
        }
        
    }
</script>

</html>

virtualdict/templates/concept.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<main class="container py-3 mb-5">
    <div class="card card-body mb-4 m-2 ">
        <header class="d-flex justify-content-between">
            <h1 class="card-title">{{concept.title}}</h2>
        </header>
        <ul class="list-unstyled">
            <li class="bd-links-span-all mt-1 mb-3 mx-4 border-top"></li>

            <li>
                <p class="card-text" style="font-size: larger!important;">{{concept.definition}}</p>
            </li>

            <li>
                <p class="card-text" style="font-size: larger!important;">{{concept.exampleText}}</p>
            </li>
        </ul>
        <div class="text-center">
            {% if concept.exampleImg %}
                <img src="{{concept.exampleImg.url}}" alt="example img" style="height: auto;" width="200px" class="img-thumbnail btn" data-toggle="modal" data-target="#largerimg" onclick="store(this.src)">
            {% endif %}
        </div>
        <div class="text-end">
            <p style="font-style: italic;">Fuente: {{concept.source}}</p>
              <p style="font-style: italic;">Autor: 
                <a href="{% url 'profile' concept.user.username %}">
                <b>{{concept.user.username}}</b> 
              </a>
              </p>
            </a>
            
        </div>


        <form action="{% url 'concept_reaction' concept.id %}" method="POST">
            {% csrf_token %}
            <div class="d-flex flex-row">
                <div class="col-auto">   
                    
                    <button class="{% if user_review.review %} btn btn-outline-success mb-3 {% else %} btn mb-3 {% endif %}" 
                    id="green" type="submit" value="like" name="reaction"><i class="fa fa-thumbs-up fa-lg" aria-hidden="true"></i>{{positive}}</button>
                </div>
                <div class="col-auto">
                    <button class="{% if user_review.review is none %} btn mb-3 {% elif user_review.review is False %} btn btn-outline-danger mb-3 {% else %} btn mb-3  {% endif %}"
                    id="red" type="submit" value="False" name="reaction"><i class="fa fa-thumbs-down fa-lg" aria-hidden="true"></i>{{negative}}</button>
                </div>
            </div>

        </form>

         {% if concept.user.username == actual_user %}

         <div class="d-flex flex-row">
          <div class="col-auto">
              <a class=" btn btn-success" href="{% url 'concept_detail' concept.id %}">Editar</a>
          </div>

          <div class="col-auto">
              <a class=" btn btn-danger" href="{% url 'concept_delete' concept.id  %}">Borrar</a>
          </div>
          
        </div>
          
         {% endif %}
            

    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-lg-6">
          <div class="card card-body" >
            <div class="card-body p-4">
              
              <div class="form-outline mb-4">
                    <form class="d-flex " action="{% url 'concept_comment' concept.id %}" method="POST" >
                        {% csrf_token %}
                        <textarea class="form-control me-2" type="comentario" id="comentario" name="comentario" placeholder="Escribe un comentario.."></textarea>
                        <button class="btn btn-primary" type="submit">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
                          </svg>
                        </button>
                      </form>
            </div>



              {% for comentario in comentarios %}
                <!-- .0 = perfil-->
                <!-- .1 = comentario-->
              <div class="card mb-4">
                <div class="card-body">
                  <p>{{comentario.1.texto}}</p>
                  <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                      <img src="{% if comentario.0.foto %}{{ comentario.0.foto.url }}{% else %} /static/images/empty_pfp.png {% endif %}"
                      width="25"
                      height="25"> 
                      <a href="{% url 'profile' comentario.1.user.username %}">

                      <!--img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp" alt="avatar" width="25"
                        height="25" /-->
                      <b class="small mb-0 ms-2">{{comentario.1.user.username}}</b>
                    </a>
                      <p class="small mb-0 ms-2">{{comentario.1.fecha_publicacion}}</p>
                    </div>
                  </div>
                </div>
              </div>
                
              {% endfor %}
      
            </div>
          </div>
        </div>
      </div>

</main>

<script src="https://use.fontawesome.com/fe459689b4.js"></script>
<script>
    function search(ele) {
        if(event.key === 'Enter') {
            alert(ele.value);        
        }
    }
</script>



{% endblock %}

virtualdict/templates/settings.html
{% extends 'base.html' %}

{% block content %}

<main class="container py-3 mb-5">


    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4">Editar Perfil</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
    
                    <!-- Campo Nombre -->
                    <div class="form-group">
                        <label for="id_nombre">Nombre:</label>
                        <input type="text" class="form-control" id="id_nombre" name="nombre" value="{{ user.nombre }}">
                    </div>
    
                    <!-- Campo Correo Electrónico -->
                    <div class="form-group">
                        <label for="id_correo">Correo Electrónico:</label>
                        <input type="email" class="form-control" id="id_correo" name="correo" value="{{ user.correo }}">
                    </div>
    
                    <!-- Campo Contraseña -->
                    <div class="form-group">
                        <label for="id_contraseña">Contraseña:</label>
                        <input type="password" class="form-control" id="id_contraseña" name="contraseña">
                    </div>
    
                    <!-- Campo Foto de Perfil -->
                    <div class="form-group">
                        <label for="id_foto">Foto de Perfil:</label>
                        <input type="file" class="form-control-file" id="id_foto" name="foto">
                        {% if user.foto %}
                            <img src="{{ user.foto.url }}" class="mt-2" width="100" height="100" alt="Foto de Perfil">
                        {% endif %}
                    </div>
    
                    <!-- Campo Biografía -->
                    <div class="form-group">
                        <label for="id_biografia">Biografía:</label>
                        <textarea class="form-control" id="id_biografia" name="biografia" rows="4">{{ user.biografia }}</textarea>
                    </div>
    
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                </form>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


</main>

{% endblock %}